# Generated by Django 5.2.4 on 2025-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.BigIntegerField(),
        ),
    ]
